name: "Decidim auto update"
on: 
  schedule:
    - cron: "*/10 * * * *"
env:
  RUBY_VERSION: 3.1.1
  NODE_VERSION: 16.9.1
  REDIS_URL:

jobs:
  main:
    name: Update code
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm get cache)-decidim-populate-redesign"
        shell: "bash"
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-
      - run: ./bin/decidim_auto_update.sh
        name: Run decidim auto update
        shell: "bash"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_email: "fernando@populate.tools"
          message: "Update decidim"
