name: "Decidim auto update"
on:
  schedule:
    - cron: "*/10 7-19 * * 1-5"
env:
  RUBY_VERSION: 3.1.1
  NODE_VERSION: 16.9.1
  REDIS_URL:

jobs:
  main:
    name: Update code
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Check SHA
        id: check-sha
        # When there're no SHA changes, step returns 0 (success), but the next steps won't run
        # When there are, step returns 1 (fail), the job continue-on-error, and the next steps will run
        continue-on-error: true
        run: |
          LOCAL_DECIDIM_SHA=$(grep revision Gemfile.lock | awk '{print $2}')
          REMOTE_DECIDIM_SHA=$(git ls-remote https://github.com/decidim/decidim.git | grep feature/redesign-staging | awk '{print $1}')
          [[ $LOCAL_DECIDIM_SHA == $REMOTE_DECIDIM_SHA ]] && { echo "Local and remote Decidim SHA match. Aborting."; exit 0; } || exit 1
      - uses: ruby/setup-ruby@v1
        if: failure()
        with:
          ruby-version: 3.1.1
      - uses: actions/setup-node@v3
        if: failure()
        with:
          node-version: 16.13.0
      - name: Get npm cache directory path
        if: failure()
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm get cache)-decidim-populate-redesign"
        shell: "bash"
      - uses: actions/cache@v3
        if: failure()
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-
      - run: ./bin/decidim_auto_update.sh
        if: failure()
        name: Run decidim auto update
        shell: "bash"
      - name: Commit & Push changes
        if: failure()
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_email: "fernando@populate.tools"
          message: "Update decidim"
      - name: Push to dokku
        if: failure()
        uses: dokku/github-action@master
        with:
          # specify the `main` branch as the remote branch to push to
          branch: 'master'
          git_remote_url: 'ssh://dokku@server-staging03.populate.tools/~/decidim-populate-redesign'
          ssh_private_key: ${{ secrets.DOKKU_DEPLOY_SSH_KEY }}
